### PR TITLE
Add the ability to create a schema with an arbitrary name

### LINKED ISSUE #4: Allow arbitrary subject names
It would be nice if the library allowed using arbitrary subject names instead of appending `-key` or `-value`.

### PR DESCRIPTION
**Pull request by arkiaconsulting**
Resolve #4

### CODE REVIEW

**Comment by AtakanColak** [comment]
@arkiaconsulting thank you for the PR, this is how I wanted to rework the package into but didn't take the time to do so. Maybe we should do an emergency patch like this so others can use it until we eventually do incorporate this as the main methods. @riferrei what do you think?

**Comment by arkiaconsulting** [comment]
@AtakanColak Yep, I think the lack of this feature was a show stopper, important enough to release a patch

**Comment by arkiaconsulting** [comment]
@AtakanColak @riferrei Could we complete ?

**Comment by AtakanColak** [comment]
@arkiaconsulting I was waiting for an answer from @riferrei but you are right, this can't wait any longer. I will conduct necessary checks and tests first thing tomorrow.

**Comment by riferrei** [comment]
Sorry for the delay in responding. Please proceed as planned. This works look good 👌🏻

**Comment by AtakanColak** [comment]
Spent more time than I should have in order get a schema registry image up and running. I couldn't manage to do so, but the project builds and runs, so I will postpone proper testing to the actual rework I'm planning. Accepted.

**Pull request merged**
