### PR TITLE
add producer protobuf example

### PR DESCRIPTION
**Pull request by bigkraig**
run `tilt up` once you have [tilt](https://tilt.dev) installed. I didn't have time this morning to show a consumer but it is close to the producer.

### CODE REVIEW

**Comment by AtakanColak** [comment]
Hi,

I've just finished my work on #86 which uses Docker and Docker Compose for integration testing and adds GitHub Action for it.

Would you be willing to use that structure rather than tilt? 

Either ways, thank you for the PR, I'm not sure when I'll find the time to review it so perhaps @riferrei could help out.

**Comment by riferrei** [comment]
I think this PR brings enormous value to this repo, as many people are shifting from Avro to Protobuf these days. Myself included. 😅

However, I would rather avoid introducing new technologies to this repo. Docker/Docker Compose are more common options for integration testing, so maybe adapt this PR to use the changes brought by @AtakanColak?

Tilt is great, BTW. I just want to minimize the friction of people onboarding with this library.

**Comment by AtakanColak** [comment]
Hi @bigkraig, are there any updates on this? This contribution is very valuable 💎

**Comment by bigkraig** [comment]
Hey sorry everybody, I've since noticed that Confluent very recently [added a go client](https://github.com/confluentinc/confluent-kafka-go/tree/master/schemaregistry) for the schema registry and have moved over to that.

**Comment by AtakanColak** [comment]
Hi, I'm closing this PR due to timeout, but am adding it to TODO list.

**Pull request closed without merging**
