### PR TITLE
Fix test errors + add CI/CD pipeline

### PR DESCRIPTION
**Pull request by mattfung**
- Existing unit tests are failing due to outdated error logic (fixed)
- Add circleci pipeline config
  - For example, I enabled circleci on my forked repo: https://app.circleci.com/pipelines/github/mattfung/srclient it's all free, and simple to set up
  - Badges dont work with the `adoc` readme format. If you would like to convert the doc to markdown, I dont mind opening a PR

Comments welcome, thanks for your work with the repo

### CODE REVIEW

**Comment by AtakanColak** [comment]
Thank you for your PR, seems fine, could you convert to doc to markdown with adding the circle ci badge please?

**Comment by mattfung** [comment]
@AtakanColak  I updated the PR to convert `README.adoc` to github markdown.
The CircleCI badge link I created is for the `riferrei/srclient` repository. At the moment, the CircleCI configuration for `riferrei/srclient` does not exist, hence the link will appear broken. Once CircleCI integration is set up for this repository, the link should work.

**Comment by AtakanColak** [comment]
@riferrei you need to set up circle ci as repo admin.

**Comment by riferrei** [comment]
Not sure if I did it correctly, but it seems to be enabled. There is a branch called "circleci-project-setup" that I ran successfully.

**Comment by riferrei** [comment]
OK 👍🏻

**Comment by riferrei** [comment]
See if now works.

**Comment by AtakanColak** [comment]
I can't confirm, and won't be able to reply until tomorrow.

**Comment by mattfung** [comment]
@riferrei I see some builds in the pipeline for branch `circleci-project-setup`, but no builds in the master branch.
Can you please take a look at the configuration for the master branch? You may have to set up the project again
https://app.circleci.com/pipelines/github/riferrei/srclient?branch=master&filter=all

**Comment by riferrei** [comment]
For some weird reason, CircleCI is not allowing me to commit the configuration to the master branch. It might be my lack of knowledge of how CircleCI works, but I cannot complete this configuration. Happy to provide access to any of you to set this up.

**Comment by mattfung** [comment]
That's odd, are you able to select the option to use an existing [circleci configuration](https://github.com/riferrei/srclient/blob/master/.circleci/config.yml)? I don't mind taking a look as well if access can be provided..

**Comment by riferrei** [comment]
Hi @mattfung, I added you as a collaborator on this repo.

**Comment by mattfung** [comment]
@riferrei thanks, I tried to set up `master` branch with existing config, but there was strangely no effect. I then pushed the same commit a new branch to github , `circleci-test-2`, and the pipeline automatically ran without any config on circleci side.

Hopefully, when we push a new commit to `master`, the pipeline will build. To test this, I created a PR and added a line of documentation (#65). Please review and merge if it looks good.

**Comment by riferrei** [comment]
Just merged 😊

**Pull request merged**
