### PR TITLE
Fix createSchema method

### PR DESCRIPTION
**Pull request by kompl**

### CODE REVIEW

**Comment by AtakanColak** [comment]
Thank you for this PR.

Is this a behaviour change with CP v6 or v7, or did this bug persist all along?

As I'm not actively working on this repository, I'll need someone else to test this fix to approve this. I'll assign @riferrei for the time being.

If this takes a while and there are others who came across this bug before, please do comment so I'll consider approving without tests.

**Comment by kompl** [comment]
> Thank you for this PR.
> 
> Is this a behaviour change with CP v6 or v7, or did this bug persist all along?
> 
I don't know, I started working with CP today and noticed this behaviour.
Pay attention to the method [documentation|https://docs.confluent.io/platform/current/schema-registry/develop/api.html#post--subjects-(string-%20subject)-versions]

**Comment by riferrei** [comment]
Hi @kompl,

First of all, thank you for the PR. Could you test this with Confluent Cloud to see if this bug is reproducible?

To make things easy for you, I just created one cluster on Confluent Cloud so you can test it:

**API endpoint**: https://psrc-4yovk.us-east-2.aws.confluent.cloud

**Key**: KQDXVGPDVOT2MJT6
**Secret**: 0OjdBGenwP2tmDY9nABHAS+gERqsbXO2uyrbMkUKfsZAheTln8khO1Wcd6eUuU89

Example:

curl -s -u <API_KEY>:<API_SECRET> GET https://psrc-4yovk.us-east-2.aws.confluent.cloud/subjects

With the srClient API, just use the `SetCredentials()` function to provide the key and secret as username and password.

If the problem persists on Confluent Cloud, we can go ahead and approve the PR. Confluent Cloud always uses the latest and stable bits of Confluent Platform, which includes SR. And it is pointless to have this library if not fully compatible with the latest release. Alternatively, we can try to do things like pulling the current version of SR from the API (not sure if this is possible right now) and based on the value of the version, decide how to perform the calls. This way we can promote backward compatibility.

**Comment by kompl** [comment]
> 

bug reproduced

**Comment by kompl** [comment]
> Hi @kompl,
> 
> First of all, thank you for the PR. Could you test this with Confluent Cloud to see if this bug is reproducible?
> 
> To make things easy for you, I just created one cluster on Confluent Cloud so you can test it:
> 
> **API endpoint**: https://psrc-4yovk.us-east-2.aws.confluent.cloud
> 
> **Key**: KQDXVGPDVOT2MJT6 **Secret**: 0OjdBGenwP2tmDY9nABHAS+gERqsbXO2uyrbMkUKfsZAheTln8khO1Wcd6eUuU89
> 
> Example:
> 
> `curl -s -u <API_KEY>:<API_SECRET> GET https://psrc-4yovk.us-east-2.aws.confluent.cloud/subjects`
> 
> With the srClient API, just use the `SetCredentials()` function to provide the key and secret as username and password.
> 
> If the problem persists on Confluent Cloud, we can go ahead and approve the PR. Confluent Cloud always uses the latest and stable bits of Confluent Platform, which includes SR. And it is pointless to have this library if not fully compatible with the latest release. Alternatively, we can try to do things like pulling the current version of SR from the API (not sure if this is possible right now) and based on the value of the version, decide how to perform the calls. This way we can promote backward compatibility.

I created two schemes, first I made ChargeLogId with the int type (id 100017), the second with the long type (id 100018). After that, I again made a post request with int, and received the id of the previous scheme (id 100017) in the response. And the request for the last scheme returns me a scheme with the type long and id 100018.

**Review by riferrei — APPROVED** [review]
The finding seems legit, as well as for the fix. Thanks for this @kompl 👍🏻

**Comment by riferrei** [comment]
Thanks for validating this issue. I think your fix will add significant value to the code. If I can trouble you with one more thing before merging this into the main, could you also remove the comment I had made above the code? My comments don't make sense anymore, as the race-condition hypotheses won't occur anymore.

**Pull request merged**
