### PR TITLE
Add references to Schema

### PR DESCRIPTION
**Pull request by gustavooferreira**
According to the schema registry API docs, we get a list of references when reading or creating a new schema.

Reference: https://docs.confluent.io/platform/current/schema-registry/develop/api.html#post--subjects-(string-%20subject)-versions

### CODE REVIEW

**Comment by AtakanColak** [comment]
Hello, thanks for your PR.

I didn't have any experience with the schema references before, so I must ask, doesn't current Reference struct already handle that in the package?

**Comment by gustavooferreira** [comment]
No, currently this SDK only allows us to set references when creating new schemas. But the API also allows you to do look-ups on schemas to retrieve their references.

The reference link I posted above shows an example of that, but another example is:
```
▶ curl -s -X GET http://localhost:8081/schemas/ids/8 | jq .
{
  "schemaType": "PROTOBUF",
  "schema": "<proto file content here>",
  "references": [
    {
      "name": "google/protobuf/timestamp.proto",
      "subject": "google/protobuf/timestamp.proto",
      "version": 1
    },
    {
      "name": "google/protobuf/any.proto",
      "subject": "google/protobuf/any.proto",
      "version": 1
    },
    {
      "name": "shared/header/v1/header.proto",
      "subject": "shared/header/v1/header.proto",
      "version": 1
    }
  ]
}
```

As you can see, asking for the schema with ID 8 retrieved not only the schema itself but also all its references.

**Comment by riferrei** [comment]
This seems to be a nice add-on to the project. Thanks for the PR @gustavooferreira 🎉

And it makes sense to enable developers to retrieve existing references (if any) of the schema — I have seen some people using this approach when the design of the schema is broken down into multiple domains. My only concern, @gustavooferreira, is that the code doesn't handle any edge cases about the possibility of no reference exist. Did you test this scenario?

If this is safe and won't break the existing code, I think it is OK to approve the PR, so this is my LGTM. What do you think, @AtakanColak?

**Comment by gustavooferreira** [comment]
Hi @riferrei, first of all, thank you and @AtakanColak and all the others who have built and maintained an SDK in golang for the schema registry.

With regards to your question, I am using this code (using a `replace` in my go.mod file for the time being while this MR doesn't get merged) and I have no problems with it.

The reason for that is that if the schema registry doesn't return a "references" array, the references field in the `Schema` and `schemaResponse` struct won't be populated, therefore they will be nil slices.
It's the responsibility of the caller to either check the length of the `references` slice or to loop through the slice.

Getting the length of the references slice, `len()`, on a nil slice or empty slice always returns zero, so that won't cause a panic.

The same applies to people who try to immediately use the `references` field in a for-loop. The for-loop just won't be executed if the `references` field is nil.

For example:
```golang
for _, ref := range schema.References() {
		fmt.Printf("ref: %+v\n", ref)
}
```
The snippet above just won't execute if the `references` slice returned is nil. It won't panic.

As for the existing code, the code won't break because this is a new field being added to the struct so the current code won't be using this field yet anyway.

**Comment by riferrei** [comment]
Understood. Make sense. Could you please then add a test case for this scenario? That way, we can better measure this functionality and make sure the existing tests won't break either.

**Comment by gustavooferreira** [comment]
Added 2 test cases, one for when there are references and another one for when there aren't, i.e., `references = nil`.

**Comment by riferrei** [comment]
Thanks for the contribution, @gustavooferreira 👍🏻

**Comment by gustavooferreira** [comment]
No worries @riferrei. Can we also have the version bumped, please? So I can reference a proper version in my `go.mod` file?

**Comment by riferrei** [comment]
Do you mean for the release?

**Comment by gustavooferreira** [comment]
Yeah, I don't know what's your policy on that, but if you could make a minor release so I can reference that version in my code, that would be very much appreciated!

**Comment by riferrei** [comment]
My policy is making developers happy. Just created the v0.3.1 release:

https://github.com/riferrei/srclient/releases/tag/v0.3.1

**Comment by gustavooferreira** [comment]
Fantastic! Thank you very much @riferrei!

**Pull request merged**
